plugin:
    name: 'logingrupa.metapixelshopaholic::lang.plugin.name'
    description: 'logingrupa.metapixelshopaholic::lang.plugin.description'
    author: Logingrupa
    icon: icon-shopping-cart
    homepage: 'https://logingrupa.lv'
